AS = nasm
CC = gcc
LD = ld
CFLAGS = -ffreestanding -m64 -nostdlib -Wall -Wextra \
         -Iinclude \
         -Ikernel/include \
         -Idrivers/vga \
         -Idrivers/keyboard \
         -Idrivers/timer \
         -Igui/include \
         -Ifile_explorer/include \
         -Ifs/fat32
LDFLAGS = -T linker.ld -nostdlib

all: scooter_os.bin

boot.bin: boot/boot_sect.asm
	$(AS) -f bin boot/boot_sect.asm -o boot.bin

kernel.elf: kernel/src/main.c kernel/src/gdt.c kernel/src/gdt_flush.s \
           kernel/src/idt.c kernel/src/io.c kernel/src/interrupts.s \
           kernel/src/memory.c \
           drivers/vga/vga.c drivers/keyboard/keyboard.c \
           drivers/timer/timer.c \
           gui/src/window_manager.c \
           file_explorer/src/explorer.c \
           fs/fat32/fat32.c
	$(CC) $(CFLAGS) -c kernel/src/main.c -o kernel/main.o
	$(CC) $(CFLAGS) -c kernel/src/gdt.c -o kernel/gdt.o
	$(AS) -f elf64 kernel/src/gdt_flush.s -o kernel/gdt_flush.o
	$(CC) $(CFLAGS) -c kernel/src/idt.c -o kernel/idt.o
	$(CC) $(CFLAGS) -c kernel/src/io.c -o kernel/io.o
	$(AS) -f elf64 kernel/src/interrupts.s -o kernel/interrupts.o
	$(CC) $(CFLAGS) -c kernel/src/memory.c -o kernel/memory.o
	$(CC) $(CFLAGS) -c drivers/vga/vga.c -o drivers/vga/vga.o
	$(CC) $(CFLAGS) -c drivers/keyboard/keyboard.c -o drivers/keyboard/keyboard.o
	$(CC) $(CFLAGS) -c drivers/timer/timer.c -o drivers/timer/timer.o
	$(CC) $(CFLAGS) -c gui/src/window_manager.c -o gui/src/window_manager.o
	$(CC) $(CFLAGS) -c file_explorer/src/explorer.c -o file_explorer/src/explorer.o
	$(CC) $(CFLAGS) -c fs/fat32/fat32.c -o fs/fat32/fat32.o
	$(LD) -nostdlib -T linker.ld --oformat=elf64-x86-64 \
		kernel/main.o kernel/gdt.o kernel/gdt_flush.o \
		kernel/idt.o kernel/io.o kernel/interrupts.o kernel/memory.o \
		 drivers/vga/vga.o drivers/keyboard/keyboard.o drivers/timer/timer.o \
		 gui/src/window_manager.o file_explorer/src/explorer.o fs/fat32/fat32.o -o kernel.elf

scooter_os.bin: boot.bin kernel.elf
	objcopy -O binary kernel.elf kernel.bin
	cat boot.bin kernel.bin > scooter_os.bin

clean:
	rm -f boot.bin kernel.elf kernel/*.o drivers/vga/*.o drivers/keyboard/*.o drivers/timer/*.o \
	      gui/src/*.o file_explorer/src/*.o fs/fat32/*.o scooter_os.bin

run: all
	"C:\Program Files\qemu\qemu-system-x86_64.exe" -drive format=raw,file=scooter_os.bin